#!/usr/bin/env bash
# gen-docs.sh regenerates the static API documentation site into ./docs.
#
# The site is generated by golds (https://go101.org/golds), which reads the
# doc comments and source of the module directly, so the reference pages can
# never drift from the code. The output is a fully static, self-contained
# site — no server-side rendering, no pkg.go.dev dependency — browse it by
# opening docs/index.html, serving the folder, or running serve-docs.sh.
#
# Usage:
#   ./scripts/gen-docs.sh
#
# The golds version is pinned so regeneration is reproducible.
set -euo pipefail
cd "$(dirname "$0")/.."

GOLDS_VERSION="v0.8.7"

go run "go101.org/golds@${GOLDS_VERSION}" \
  -gen \
  -dir=docs \
  -wdpkgs-listing=solo \
  -theme=light \
  -nouses \
  -nostats \
  -only-list-exporteds \
  -source-code-reading=external \
  -footer=none \
  -silent \
  ./...

echo
echo "Docs generated in docs/ (about 11 MB)."
echo "Open docs/index.html in a browser, run ./scripts/serve-docs.sh,"
echo "or serve the folder with any static file server."
